Name: Container
on: push

jobs: 
  node-docker:
    runs-on: ubuntu-latest
    Container: node:13.5.0-alpine3.10
    steps: 
      - name: Log node version
        run: |
          node -V
          cat /etc/os-release 
