name: Matrix
on: pull_request

jobs:
  node-version:
    strategy:
      matrix: 
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6,8,10]
    runs-on: ${{ matrix.os }}
    steps: 
    - name: Log node version  
      run: node -v
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version:  ${{ matrix.node_version }}
    - name: Log node version
      run: node -v
        
        