name: Python Action

on: push

jobs:
  run-python-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: sum
        uses: luisgustavobueno/First-Action@master
